---
- hosts: servers
  gather_facts: no

  tasks:
    - name: include variables
      include_vars: roles/rtorrent/vars/main.yml

    - name: copy torrent files to watch directory
      copy:
        src="{{item}}"
        dest="{{torrents_base_path}}/{{torrents_watch_path}}/"
        owner={{torrents_user}}
        group={{torrents_user}}
      with_fileglob:
        - ~/Downloads/*.torrent

    - name: remove local torrent files
      local_action: command rm "{{item}}"
      with_fileglob:
        - ~/Downloads/*.torrent
