---
- hosts: servers
  gather_facts: no

  tasks:
    - name: include variables
      include_vars: roles/transmission/vars/main.yml

    - name: sync remote files to local directory
      synchronize:
        mode=pull
        src={{transmission_base_path}}/{{transmission_downloads_path}}/
        dest=~/Music/torrents

    - name: copy torrent files to watch directory
      sudo: yes
      copy:
        src="{{item}}"
        dest="{{transmission_base_path}}/{{transmission_watch_path}}/"
        owner=debian-transmission
        group=debian-transmission
      with_fileglob:
        - ~/Downloads/*.torrent

    - name: remove local torrent files
      local_action: command rm "{{item}}"
      with_fileglob:
        - ~/Downloads/*.torrent
