- name: update apt caches
  apt: update_cache=yes cache_valid_time=3600

- name: update apt installation
  apt: upgrade=dist
  register: apt_updated

- name: reboot server
  command: reboot
  async: 0
  poll: 0
  ignore_errors: true
  when: apt_updated.changed

- name: wait for server to come online
  local_action:
    wait_for
    host={{inventory_hostname}}
    port=22
    state=started
    delay=3
    timeout=300
  sudo: false
  when: apt_updated.changed
